(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.AIHubCapabilities=factory();})(globalThis,function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const domains={video:'视频',image:'图像',audio:'语音',code:'代码',research:'研究',document:'文档',automation:'自动化'};
  const rows=v=>Array.isArray(v)?v:[];
  const date=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'尚无心跳记录';
  const json=v=>JSON.stringify(v??{},null,2);
  function capture(el){const values={};for(const id of ['query','domain','kind','tool','task-query','task-domain','project','title','inputs'])values[id]=el?.querySelector('#cp-'+id)?.value||'';return{values,selected:el?.dataset.cpSelected||'',root:el?.dataset.cpRoot||''};}
  function cards(items,selected){return rows(items).map(c=>`<article class="panel cp-card"><div class="cp-card-heading"><span class="badge">${c.kind==='skill'?'Skill':'MCP 接口'}</span><h3>${esc(c.name)}</h3></div><p>${esc(c.description)}</p><div class="cp-tags">${rows(c.domains).map(d=>`<span>${esc(domains[d]||d)}</span>`).join('')}</div><div class="cp-evidence"><div><small>声明</small><strong>客户端已声明</strong><span>来源 ${esc(c.provider||'未注明')} / ${esc(c.server||'未注明服务')}</span></div><div><small>工作端心跳</small><strong>${c.client_online?'近期有心跳':'未见近期心跳'}</strong><span>${esc(date(c.last_seen))}</span></div><div><small>执行验证</small><strong>未经执行验证</strong><span>排队交给 ${esc(c.target_tool||'指定工作端')}</span></div></div>${rows(c.reasons).length?`<div class="cp-match"><strong>声明匹配理由</strong>${rows(c.reasons).map(r=>`<p>${esc(r)}</p>`).join('')}</div>`:''}<details><summary>输入要求、产物与限制</summary><p>客户端：${esc(c.client_id)} · 能力来源与执行端分别登记。</p><strong>输入结构</strong><pre>${esc(json(c.inputs))}</pre><strong>预期产物</strong><pre>${esc(json(c.outputs||[]))}</pre><strong>约束</strong><pre>${esc(json(c.constraints||[]))}</pre><p>成本 / 速度 / 质量：${esc(c.hints?.cost||'未声明')} / ${esc(c.hints?.speed||'未声明')} / ${esc(c.hints?.quality||'未声明')}（均为声明，未实测）</p></details><div class="cp-card-footer"><small>队列交接 · 需工作端领取执行</small><button class="btn small ${c.id===selected?'primary':''}" data-cp-select="${esc(c.id)}">${c.id===selected?'已选此能力':'选入任务'}</button></div></article>`).join('')||'<div class="cp-empty">当前条件下没有已声明能力。先连接工作端发布能力声明；本机发现的 Skill 仅是接入线索。</div>';}
  function discoverHTML(data){return `<p>发现 ${rows(data.suggestions).length} 条本机 Skill 线索；${data.truncated?'扫描未完整。':''}跳过 ${esc(data.skipped||0)} 项。尚未发布到能力目录，不能从这里直接执行。</p>${rows(data.suggestions).map(s=>`<article><strong>${esc(s.name)}</strong><span class="badge">${esc(s.tool)}</span><p>${esc(s.description||'未提供单行说明')}</p><small>${esc(s.path)}</small></article>`).join('')}`;}
  function createPage({api,heading}){let generation=0;return async(el,params=new URLSearchParams(),restored)=>{
    const run=++generation,active=()=>el.isConnected&&generation===run;
    let items=[],matches=null,selected=restored?.selected||'',root='',busy=false,request=0,matchRequest=0;
    const get=id=>el.querySelector('#cp-'+id),error=e=>{get('error').textContent=e?.message||String(e||'');};
    const post=(name,body)=>api('/api/capabilities/'+name,{body:root?{...body,_workspace_root:root}:body});
    el.classList?.add('capabilities-page');el.innerHTML=(heading?heading('能力与调度','查看各工具声明的 Skill 与接口，把任务交给合适的工作端。','CAPABILITY DIRECTORY'):'<h2>能力与调度</h2>')+`<div class="cp-intro"><p>曜核负责发现、匹配与任务交接；创作内容仍由原工具处理，执行结果登记到统一项目。</p><button id="cp-refresh" class="btn small">刷新目录</button></div><div id="cp-error" class="cp-error" role="alert"></div><div class="cp-coverage"><strong id="cp-count">正在读取声明…</strong><p>已声明 ≠ 可立即调用。近期心跳不保证实时在线，所有能力均未经执行验证；排队也不代表已开始运行。</p><a href="#/collaboration?tab=connect">配置工作端接入</a></div><div class="cp-layout"><section><form id="cp-filter-form" class="cp-filters"><label>目录关键词<input id="cp-query" type="search" placeholder="名称、说明、提供方"></label><label>能力领域<select id="cp-domain"><option value="">全部领域</option>${Object.entries(domains).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label><label>类型<select id="cp-kind"><option value="">全部类型</option><option value="skill">Skill</option><option value="mcp_tool">MCP 接口</option></select></label><label>执行工作端<select id="cp-tool"><option value="">全部工作端</option></select></label><button type="submit" class="btn small">筛选目录</button></form><div class="cp-actions"><span id="cp-list-caption">当前工作区的客户端声明</span><button id="cp-clear-match" class="btn small ghost" hidden>返回全部声明</button></div><div id="cp-list" class="cp-catalog"></div><details class="panel cp-discovery"><summary>本机 Skill 接入线索（只读）</summary><p>只读取已知 Skill 目录的声明头，不读取原生会话，不执行 Skill，也不自动发布能力。</p><button id="cp-discover" class="btn small">发现本机 Skill</button><div id="cp-discover-results" role="status"></div></details></section><aside class="panel cp-task-panel"><div class="panel-head"><h3>任务匹配与交接</h3></div><div class="body"><form id="cp-match-form" class="cp-task-fields"><label>要完成的工作<textarea id="cp-task-query" rows="3" placeholder="例如：整理资料并输出项目报告" required maxlength="2000"></textarea></label><label>期望领域<select id="cp-task-domain"><option value="">从描述匹配</option>${Object.entries(domains).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label><button id="cp-match" class="btn">匹配声明能力</button></form><p class="cp-legend">按声明文字与领域推荐，不比较真实质量、成本或成功率。</p><div id="cp-selection" class="cp-selection">从目录选择一个能力后，核对输入要求。</div><form id="cp-dispatch-form" class="cp-task-fields"><label>归档项目<input id="cp-project" required maxlength="120" placeholder="统一任务所属项目"></label><label>任务标题<input id="cp-title" required maxlength="200" placeholder="给工作端的具体任务"></label><label>交接输入（JSON 对象）<textarea id="cp-inputs" rows="7" spellcheck="false" required>{}</textarea></label><p class="cp-legend">输入须符合所选能力结构；请勿粘贴密钥。工作端领取后核对权限与费用，执行后登记报告和产物。</p><button id="cp-dispatch" class="btn primary" disabled>创建统一任务并排队</button></form><div id="cp-result" class="cp-result" role="status" aria-live="polite"></div></div></aside></div>`;
    for(const [id,value]of Object.entries(restored?.values||{}))if(get(id))get(id).value=value;
    if(!get('inputs').value)get('inputs').value='{}';if(!restored)get('domain').value=params.get('domain')||'';
    function current(){return items.find(i=>i.id===selected)||(matches||[]).find(i=>i.id===selected);}
    function selection(){el.dataset.cpSelected=selected;const item=current();get('dispatch').disabled=busy||!item;get('selection').innerHTML=item?`<strong>${esc(item.name)}</strong><p>${esc(item.provider)} → ${esc(item.target_tool)}</p><details open><summary>输入结构（客户端声明）</summary><pre>${esc(json(item.inputs))}</pre></details>`:'从目录选择一个能力后，核对输入要求。';}
    function render(){const query=get('query').value.trim().toLowerCase(),domain=get('domain').value,kind=get('kind').value,tool=get('tool').value;
      const visible=(matches??items).filter(c=>(!domain||rows(c.domains).includes(domain))&&(!kind||c.kind===kind)&&(!tool||c.target_tool===tool)&&(!query||[c.name,c.description,c.provider,c.server,...rows(c.tags)].join(' ').toLowerCase().includes(query)));
      get('list').innerHTML=cards(visible,selected);get('list-caption').textContent=`${matches===null?'客户端声明':'匹配候选'} · 当前筛选 ${visible.length} 项`;get('clear-match').hidden=matches===null;
      el.querySelectorAll('[data-cp-select]').forEach(b=>b.onclick=()=>{if(busy)return;selected=b.dataset.cpSelect;selection();render();get('project').focus?.();});
    }
    async function load(){const serial=++request;get('refresh').disabled=true;error('');try{const data=await api('/api/capabilities/list');if(!active()||serial!==request)return;const nextRoot=data.root||data.workspace_root||root;
      if((root||restored?.root)&&(root||restored.root)!==nextRoot){selected='';error('工作环境已切换，已清除旧能力选择，文字草稿保留。');}root=nextRoot;restored=restored?{...restored,root}:restored;el.dataset.cpRoot=root;
      items=rows(data.items);matches=null;++matchRequest;get('match').disabled=false;const tool=get('tool').value||restored?.values?.tool||'';get('tool').innerHTML='<option value="">全部工作端</option>'+[...new Set(items.map(i=>i.target_tool).filter(Boolean))].map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');get('tool').value=tool;if(restored?.values)restored={...restored,values:{...restored.values,tool:''}};
      if(!current())selected='';get('count').textContent=`已声明 ${items.length} 项能力 · ${items.filter(i=>i.client_online).length} 项近期有工作端心跳`;selection();render();
    }catch(e){if(active()&&serial===request){error(e);get('count').textContent='能力目录暂不可用';}}finally{if(active()&&serial===request)get('refresh').disabled=false;}}
    get('filter-form').onsubmit=e=>{e.preventDefault();render();};get('clear-match').onclick=()=>{matches=null;++matchRequest;get('match').disabled=false;render();};get('refresh').onclick=()=>!busy&&load();
    get('match-form').onsubmit=async e=>{e.preventDefault();const query=get('task-query').value.trim();if(!query){error('请先描述任务。');return;}const serial=++matchRequest;get('match').disabled=true;error('');try{const data=await post('recommend',{query,domain:get('task-domain').value});if(!active()||serial!==matchRequest)return;matches=rows(data.items);render();}catch(e){if(active()&&serial===matchRequest)error(e);}finally{if(active()&&serial===matchRequest)get('match').disabled=false;}};
    get('dispatch-form').onsubmit=async e=>{e.preventDefault();if(busy||!current())return;error('');const project=get('project').value.trim(),title=get('title').value.trim(),input_json=get('inputs').value;try{const value=JSON.parse(input_json);if(!value||Array.isArray(value)||typeof value!=='object')throw new Error();}catch(_){error('交接输入必须是有效的 JSON 对象。');return;}if(!project||!title){error('请填写归档项目和任务标题。');return;}busy=true;selection();get('refresh').disabled=true;
      try{const data=await post('dispatch',{capability_id:selected,project,title,input_json});if(!active())return;get('result').innerHTML=`<strong>任务已排队，等待工作端领取</strong><p>${esc(data.task?.title||title)} · ${esc(data.task?.id||'')}</p><p>尚未执行；在协作与记忆中查看状态、交接和产物。</p><a class="btn small" href="#/collaboration?tab=tasks">查看统一任务</a><a class="btn small" href="#/reports">查看归档报告</a>`;get('title').value='';}
      catch(e){if(active())error(e);}finally{busy=false;if(active()){selection();get('refresh').disabled=false;}}
    };
    get('discover').onclick=async()=>{get('discover').disabled=true;error('');try{const data=await api('/api/capabilities/discover');if(active())get('discover-results').innerHTML=discoverHTML(data);}catch(e){if(active())error(e);}finally{if(active())get('discover').disabled=false;}};
    await load();
  };}
  return{createPage,capture,cards,discoverHTML,esc};
});
