/* Work-end registration is metadata, never a command runner or connection test. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.AIHubHarnesses=factory();})(globalThis,function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rows=v=>Array.isArray(v)?v:[];
  const fields=['id','name','connection_mode','executable','work_dir','config_path','notes','enabled','revision'];
  const pathNames={missing:'路径不存在',file:'文件存在',directory:'目录存在',link:'链接路径',inaccessible:'无法访问',not_configured:'未填写'};
  const sourceNames={running_process:'运行进程',path:'PATH 入口',app_paths:'系统应用路径',uninstall_registry:'软件安装登记',common_location:'常见安装位置'};
  const canQueue=(items,id)=>id==='any'||rows(items).some(x=>x.id===id&&x.enabled!==false&&x.connection_mode==='mcp_stdio');
  const enabled=(items,id)=>id==='any'||rows(items).some(x=>x.id===id&&x.enabled!==false);
  function options(items,{history=false,queue=false,emptyLabel='',emptyValue='',selected='',extras=[]}={}){
    const usable=x=>x.enabled!==false&&(!queue||x.connection_mode==='mcp_stdio');
    const list=rows(items).filter(x=>history||usable(x)||x.id===selected);
    const known=new Set(list.map(x=>x.id));
    for(const id of extras)if(id&&!known.has(id)){list.push({id,name:id,historical:true});known.add(id);}
    return (emptyLabel?`<option value="${esc(emptyValue)}">${esc(emptyLabel)}</option>`:'')+list.map(x=>`<option value="${esc(x.id)}"${!history&&!usable(x)?' disabled':''}>${esc(x.name||x.id)}${x.enabled===false?'（已停用）':queue&&x.connection_mode==='manual'?'（仅手动交接）':x.historical?'（历史来源）':''}</option>`).join('');
  }
  function evidence(record={}){
    return `<div class="hc-evidence"><span>${record.detected===true?'已发现':'未发现入口'}</span><span>${record.configured===true?'已登记':record.registration_origin==='legacy_usage'?'历史使用 · 尚未登记':'未登记'}</span><span>${record.recent_heartbeat===true?'近期连接':'无近期连接证据'}</span><span>${record.invocation_verified===true?'协议调用已验证':'协议调用未验证'}</span></div>`;
  }
  const editable=r=>({id:r.id||r.suggested_id||'',name:r.name||'',connection_mode:r.connection_mode||'manual',executable:r.registered_executable??r.executable??'',work_dir:r.work_dir||'',config_path:r.config_path||'',notes:r.user_notes??(typeof r.notes==='string'?r.notes:''),enabled:r.enabled!==false,revision:Number.isInteger(r.revision)?r.revision:0});
  function shell(){return `<section class="panel hc-center"><div class="panel-head"><h3>工作端接入中心</h3><button id="hc-new" class="btn small" type="button">手动添加 / 继续草稿</button></div><div class="body"><p>先发现本机软件或手动添加，再确认保存接入声明。模板只是可选配方，其他电脑不会因此自动接入任何工作端。</p><p class="caption-note">已发现：入口存在。已登记：保存过接入声明。近期连接：最近 300 秒收到客户端心跳。协议调用已验证：MCP 客户端曾成功调用业务接口，不代表模型任务已完成。检查只读取证据，不启动第三方软件。</p><p id="hc-error" class="dialog-error" role="alert"></p><p id="hc-message" role="status" aria-live="polite"></p><div id="hc-registry"></div><section class="hc-discovery"><h4>发现本机候选</h4><p class="caption-note">只读取安装与运行线索，不启动软件。运行中不等于 MCP 在线；只有确认保存后才加入工作端列表。</p><div class="co-actions"><button id="hc-refresh" class="btn small" type="button">刷新工作端</button><button id="hc-discover" class="btn small" type="button">发现本机工作端</button></div><div id="hc-candidates" aria-live="polite"><p class="muted">点击“发现本机工作端”查找入口，也可以直接手动添加。</p></div></section><div id="hc-templates"></div><section id="hc-editor" class="hc-editor" hidden><h4 id="hc-editor-title">登记工作端</h4><form id="hc-form"><fieldset id="hc-fields" class="hc-fields"><div class="co-grid"><label>唯一标识<input id="hc-id" required maxlength="64" pattern="[a-z][a-z0-9_-]{0,63}" placeholder="例如 my-agent" autocomplete="off"></label><label>显示名称<input id="hc-name" required maxlength="120" autocomplete="off"></label><label>交接方式<select id="hc-connection_mode"><option value="manual">手动规则交接（默认）</option><option value="mcp_stdio">MCP stdio（客户端支持时选择）</option></select></label><label class="co-check"><input id="hc-enabled" type="checkbox" checked>允许项目与报告交接（MCP 模式可领取任务）</label><label class="co-wide">程序入口（可选，绝对路径）<input id="hc-executable" spellcheck="false" placeholder="只填程序文件路径，不填写启动参数"></label><label class="co-wide">工作目录（可选，绝对路径）<input id="hc-work_dir" spellcheck="false"></label><label class="co-wide">配置文件路径（可选，绝对路径）<input id="hc-config_path" spellcheck="false" placeholder="仅登记位置，不读取或修改原生配置"></label><label class="co-wide">备注<textarea id="hc-notes" maxlength="2000" rows="3" placeholder="记录用途与接入说明；不要填写令牌、密钥或环境变量"></textarea></label><input id="hc-revision" type="hidden" value="0"></div><p class="caption-note">这里不执行命令，不接收参数、环境变量或密钥。默认手动模式只提供规则与目录交接，不能建立 MCP 连接。确认该客户端支持 MCP stdio 后再选择对应模式；保存不会自动配置客户端。</p><div class="co-actions"><button id="hc-save" class="btn primary" type="submit">保存接入声明</button><button id="hc-cancel" class="btn" type="button">取消并保留草稿</button><button id="hc-reload-latest" class="btn" type="button" hidden>放弃当前草稿并加载最新登记</button></div></fieldset></form></section><section class="hc-config"><h4>取得本机 MCP 配置</h4><div class="co-grid"><label>工作端<select id="hc-config-tool"></select></label><label>客户端标识<input id="hc-client-id" maxlength="120" placeholder="为每个客户端使用独立标识" autocomplete="off"></label></div><button id="hc-config-load" class="btn small" type="button">生成本机配置片段</button><div id="hc-config-result" aria-live="polite"></div><p class="caption-note">把配置加入对应 MCP 客户端后重新连接。生成配置不代表已接通；在上方查看真实心跳和协议调用证据。</p></section></div></section>`;}
  function capture(el){return el?.harnessSnapshot?.()||null;}
  function mount(el,{api,active=()=>el.isConnected,onRegistry=()=>{},restored}={}){
    const host=el.querySelector('#co-harness');host.innerHTML=shell();
    const get=id=>el.querySelector('#hc-'+id);
    let items=[],templates=[],candidates=[],busy=false,discovering=false,configLoading=false,configHydrated=false,listSerial=0,discoverySerial=0,configSerial=0,editing='',draftKey=restored?.draftKey||restored?.editing||'$new',registryRoot='',draftRoot=restored?.root||'',drafts={};
    const draftSlot=(workspace,key)=>JSON.stringify([workspace,key]);
    for(const [key,value] of Object.entries(restored?.drafts||{}))drafts[key.startsWith('[')?key:draftSlot(restored?.root||'',key)]=value;
    const error=e=>{get('error').textContent=e?.message||String(e||'');};
    const read=()=>Object.fromEntries(fields.map(id=>[id,id==='enabled'?get(id).checked:id==='revision'?Number(get(id).value||0):get(id).value]));
    function stash(){drafts[draftSlot(draftRoot,draftKey)]=read();}
    function fill(record,existing=false,discard=false,key){stash();editing=existing?record.id:'';draftKey=key||(existing?record.id:record.id?'new:'+record.id:'$new');draftRoot=registryRoot;const slot=draftSlot(draftRoot,draftKey);if(discard)delete drafts[slot];const value=drafts[slot]||editable(record);for(const id of fields){if(id==='enabled')get(id).checked=value[id]!==false;else get(id).value=String(value[id]??'');}get('id').readOnly=existing;get('reload-latest').hidden=!existing;get('editor').hidden=false;get('editor-title').textContent=existing?'编辑工作端 · '+(record.name||record.id):'登记新的工作端';get('name').focus?.();}
    function setBusy(value){busy=value;get('fields').disabled=value;for(const id of ['new','refresh','discover','config-load'])get(id).disabled=value;el.querySelectorAll('[data-hc-action]').forEach(n=>{n.disabled=value;});}
    function notify(){onRegistry(items);}
    function render(){
      const table=list=>list.length?`<div class="table-wrap"><table class="tbl hc-table"><thead><tr><th>工作端 / 状态</th><th>交接方式 / 入口</th><th>操作</th></tr></thead><tbody>${list.map(r=>`<tr><td><b>${esc(r.name||r.id)}</b> ${r.enabled===false?'<span class="badge">已停用</span>':''}<span class="file-sub">${esc(r.id)}</span>${evidence(r)}</td><td>${r.connection_mode==='manual'?'手动规则交接':'MCP stdio'}<span class="file-sub pathline">${esc(r.executable||'未登记程序入口')}</span>${Object.entries(r.path_status||{}).filter(([,v])=>v!=='not_configured').map(([k,v])=>`<span class="file-sub">${esc({executable:'入口',work_dir:'工作目录',config_path:'配置路径'}[k]||k)}：${esc(pathNames[v]||v)}</span>`).join('')}</td><td><div class="hc-actions"><button class="btn small" data-hc-action="edit" data-hc-id="${esc(r.id)}">编辑</button><button class="btn small" data-hc-action="check" data-hc-id="${esc(r.id)}">查看接入证据</button><button class="btn small" data-hc-action="toggle" data-hc-id="${esc(r.id)}">${r.enabled===false?'重新启用':'停用'}</button></div></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">尚未登记其他工作端。</p>';
      const registered=items.filter(r=>r.registration_origin!=='legacy_usage'),legacy=items.filter(r=>r.registration_origin==='legacy_usage');
      get('registry').innerHTML='<h4>已登记工作端 · '+registered.length+' 项</h4>'+(registered.length?table(registered):'<p class="muted hc-empty">尚未登记工作端。这是新工作环境的正常状态；发现本机候选或手动添加后，确认保存即可加入。</p>')+(legacy.length?'<h4>历史使用记录 · '+legacy.length+' 项</h4><p class="caption-note">当前工作环境的旧客户端或任务曾使用这些工作端，因此保留兼容交接。它们尚未显式登记，也不表示本机已安装或当前在线；可以编辑后保存登记，或停用以保留历史。</p>'+table(legacy):'');
      get('templates').innerHTML=`<details class="hc-templates"><summary>可选接入模板 · ${templates.length} 项</summary><p class="caption-note">模板只提供名称和规则配方，不代表已安装、已登记或已连接。填表后仍需核对交接方式，再保存登记。</p><div class="hc-template-grid">${templates.map((r,index)=>`<article class="hc-template"><b>${esc(r.name||r.id)}</b><small>${esc(r.rules_support||'通用目录交接')}</small><button class="btn small" data-hc-template="${index}" type="button">使用模板填表</button></article>`).join('')||'<p class="muted">暂无可选模板，仍可手动添加。</p>'}</div></details>`;
      el.querySelectorAll('[data-hc-template]').forEach(button=>{button.onclick=()=>{if(busy||!active())return;const recipe=templates[Number(button.dataset.hcTemplate)];if(!recipe)return;const existing=items.find(r=>r.id===recipe.id);if(existing){fill(existing,true);get('message').textContent='该标识已有登记或历史记录，已打开现有条目，未重复登记。';}else{fill({id:recipe.id,name:recipe.name,connection_mode:'manual'},false,false,'template:'+recipe.id);get('message').textContent='模板已填入表单，尚未登记。默认手动交接；确认客户端支持 MCP stdio 后可自行选择。';}};});
      const selected=(!configHydrated&&restored?.configTool)||get('config-tool').value;configHydrated=true;get('config-tool').innerHTML=options(items,{selected,emptyLabel:'选择工作端'});get('config-tool').value=items.some(r=>r.id===selected)?selected:'';
      el.querySelectorAll('[data-hc-action]').forEach(button=>{button.onclick=async()=>{if(busy||!active())return;const record=items.find(r=>r.id===button.dataset.hcId);if(!record)return;const action=button.dataset.hcAction;if(action==='edit'){fill(record,true);return;}if(action==='toggle')return mutate({...editable(record),enabled:record.enabled===false},false);if(action==='check'){setBusy(true);error('');try{const result=await api('/api/harnesses/check?id='+encodeURIComponent(record.id));if(!active())return;items=items.map(r=>r.id===record.id?result:r);render();notify();get('message').textContent='已读取接入证据；没有启动或调用第三方软件。';}catch(e){if(active())error(e);}finally{if(active())setBusy(false);}}};});
    }
    async function refresh(){const serial=++listSerial;error('');try{const data=await api('/api/harnesses');if(!active()||serial!==listSerial)return;const nextRoot=data.root??data.workspace_root??registryRoot;if(registryRoot&&nextRoot!==registryRoot){++discoverySerial;discovering=false;candidates=[];get('discover').disabled=busy;get('candidates').innerHTML='<p class="muted">工作环境已切换，请重新发现本机候选。</p>';}registryRoot=nextRoot;if(!draftRoot)draftRoot=registryRoot;else if(draftRoot!==registryRoot)error('工作环境已切换，旧草稿已保留。请核对并重新选择工作端后保存。');items=rows(data.items);templates=rows(data.templates);render();notify();}catch(e){if(active()&&serial===listSerial)error(e);}}
    async function mutate(body,fromForm){if(busy||!active())return;setBusy(true);error('');get('message').textContent='正在保存接入声明…';try{const record=await api('/api/harnesses/save',{body:{...body,_workspace_root:fromForm?draftRoot:registryRoot}});if(!active())return;++listSerial;items=items.filter(r=>r.id!==record.id).concat(record);if(fromForm){delete drafts[draftSlot(draftRoot,draftKey)];editing=record.id;draftKey=record.id;draftRoot=record.root??registryRoot;for(const id of fields){const value=editable(record)[id];if(id==='enabled')get(id).checked=value;else get(id).value=String(value??'');}get('id').readOnly=true;get('reload-latest').hidden=false;}else if(editing===record.id&&draftRoot===registryRoot&&Number(get('revision').value)===body.revision){get('revision').value=String(record.revision);get('enabled').checked=record.enabled!==false;}render();notify();get('message').textContent=record.enabled===false?'工作端已停用，历史任务与报告仍可阅读。':'接入声明已保存；连接和协议调用以实际证据为准。';}catch(e){if(active()){error(e);get('message').textContent='未保存，草稿已保留。版本冲突时请核对最新登记再重试。';}}finally{if(active())setBusy(false);}}
    get('form').onsubmit=e=>{e.preventDefault();const body=read();body.id=body.id.trim();body.name=body.name.trim();if(!/^[a-z][a-z0-9_-]{0,63}$/.test(body.id)||body.id==='any'){error('标识须以小写字母开头，仅包含小写字母、数字、下划线和短横线，且不能使用 any。');return;}if(!body.name){error('请填写显示名称，草稿已保留。');return;}for(const field of ['executable','work_dir','config_path']){body[field]=body[field].trim();if(body[field]&&!/^(?:[A-Za-z]:[\\/]|\\\\[^\\]+\\[^\\]+|\/)/.test(body[field])){error('程序入口、工作目录和配置路径请使用绝对路径。草稿已保留。');return;}}return mutate(body,true);};
    get('cancel').onclick=()=>{stash();get('editor').hidden=true;get('message').textContent='草稿已保留，可选择手动添加或再次编辑继续。';};
    get('reload-latest').onclick=async()=>{
      if(busy||!editing)return;const expectedRoot=draftRoot,id=editing,serial=++listSerial;setBusy(true);error('');get('message').textContent='正在读取最新登记…';
      try{const data=await api('/api/harnesses');if(!active()||serial!==listSerial)return;const nextRoot=data.root??data.workspace_root??registryRoot;
        if(nextRoot!==expectedRoot)throw new Error('工作环境已切换，原草稿仍保留。请先选择当前工作环境中的登记。');
        const latest=rows(data.items).find(record=>record.id===id);if(!latest)throw new Error('该工作端已不在当前登记中，原草稿仍保留。');
        registryRoot=nextRoot;items=rows(data.items);templates=rows(data.templates);fill(latest,true,true);render();notify();get('message').textContent='已放弃当前草稿并载入最新登记，可在最新版本上重新编辑。';
      }catch(e){if(active()&&serial===listSerial)error(e);}finally{if(active())setBusy(false);}
    };
    get('new').onclick=()=>{if(!busy)fill({},false);};get('refresh').onclick=()=>!busy&&refresh();
    get('discover').onclick=async()=>{
      if(busy||discovering)return;discovering=true;const serial=++discoverySerial;get('discover').disabled=true;error('');
      try{
        const data=await api('/api/harnesses/discover');if(!active()||serial!==discoverySerial)return;candidates=rows(data.items);
        const scope=Array.isArray(data.scan_scope)?data.scan_scope.join('、'):typeof data.scan_scope==='string'?data.scan_scope:JSON.stringify(data.scan_scope||'');
        const statuses={ok:'已检查',complete:'已检查',partial:'部分可见',limited:'受限',unavailable:'不可用',unsupported:'不支持',error:'读取失败',skipped:'未检查'};
        const sources=Object.entries(data.sources||{}).map(([id,value])=>`<li>${esc(sourceNames[id]||id)}：${esc(statuses[value?.status]||value?.status||'状态未知')}${Number.isInteger(value?.checked)?' · 检查 '+value.checked+' 项':''}${value?.limited?' · 可见范围受限':''}${value?.truncated?' · 未完整':''}</li>`).join('');
        get('candidates').innerHTML=`<h4>本次发现 · ${candidates.length} 项</h4><p class="caption-note">扫描范围：${esc(scope||'以本机可读信息为准')}${data.truncated?' · 结果未完整':''}。发现不会自动登记，请核对后填入表单并保存。</p>${sources?`<details><summary>查看发现范围与限制</summary><ul>${sources}</ul>${rows(data.limitations).map(text=>`<p class="caption-note">${esc(text)}</p>`).join('')}</details>`:rows(data.limitations).map(text=>`<p class="caption-note">${esc(text)}</p>`).join('')}`+(candidates.length?candidates.map((r,index)=>`<article class="hc-candidate"><b>${esc(r.name||r.suggested_id)}${r.registered?' <span class="badge">已有工作端记录</span>':''}</b><span class="pathline">${esc(r.executable||'')}</span><small>${esc(rows(r.evidence_sources).map(id=>sourceNames[id]||id).join(' · ')||'入口线索')}${r.running===true?` · 观察到运行进程${Number.isInteger(r.process_count)?' '+r.process_count+' 个':''}（不代表 MCP 在线）`:''}</small><small>${esc(Array.isArray(r.evidence)?r.evidence.join('；'):r.evidence||'')}</small><button class="btn small" data-hc-candidate="${index}" type="button">填入登记表单</button></article>`).join(''):'<p class="muted hc-empty">本次未找到候选。可能尚未安装，或安装位置不在可见范围内；你仍可手动填写入口。</p>');
        el.querySelectorAll('[data-hc-candidate]').forEach(button=>{button.onclick=()=>{
          if(busy||!active())return;const candidate=candidates[Number(button.dataset.hcCandidate)];if(!candidate)return;
          const existing=items.find(r=>r.id===candidate.suggested_id);
          if(existing){fill(existing,true);get('executable').value=candidate.executable||'';}
          else fill({...candidate,id:candidate.suggested_id,connection_mode:'manual',enabled:true},false,false,'candidate:'+candidate.suggested_id+':'+candidate.executable);
          get('message').textContent='候选已填入表单，尚未保存。入口或运行线索不证明 MCP 支持，请核对交接方式和唯一标识。';
        };});
      }catch(e){if(active()&&serial===discoverySerial)error(e);}
      finally{if(active()&&serial===discoverySerial){discovering=false;get('discover').disabled=busy;}}
    };
    get('config-tool').onchange=()=>{++configSerial;configLoading=false;get('config-load').disabled=busy;get('config-result').innerHTML='';const id=get('config-tool').value;get('client-id').value=id?id+'-local':'';const record=items.find(r=>r.id===id);if(record?.connection_mode==='manual')get('config-result').innerHTML='<p class="caption-note">此工作端采用手动规则交接。请在项目目录中读取交接说明；不会生成 MCP 配置，也不表示客户端已连接。</p>';};
    get('client-id').oninput=()=>{++configSerial;configLoading=false;get('config-load').disabled=busy;get('config-result').innerHTML='';};
    get('config-load').onclick=async()=>{if(busy||configLoading)return;const id=get('config-tool').value,record=items.find(r=>r.id===id),client=get('client-id').value.trim();if(!record||record.enabled===false){error('请选择已启用的工作端。');return;}if(record.connection_mode==='manual'){get('config-tool').onchange();return;}if(!client){error('请填写独立的客户端标识。');return;}const serial=++configSerial;configLoading=true;get('config-load').disabled=true;error('');try{const result=await api('/api/harnesses/config?id='+encodeURIComponent(id)+'&client_id='+encodeURIComponent(client));if(!active()||serial!==configSerial)return;get('config-result').innerHTML=`<p>${esc(result.instructions||'把配置填写到支持 MCP stdio 的客户端。')}</p><pre class="co-code" tabindex="0">${esc(JSON.stringify(result.config,null,2))}</pre><p class="caption-note">客户端 ${esc(result.client_id||client)} · 仅生成配置，尚未证明连接或执行。</p>`;}catch(e){if(active()&&serial===configSerial)error(e);}finally{if(active()&&serial===configSerial){configLoading=false;get('config-load').disabled=false;}}};
    el.harnessSnapshot=()=>{stash();return{drafts,editing,draftKey,root:draftRoot,editorOpen:!get('editor').hidden,configTool:get('config-tool').value,clientId:get('client-id').value};};
    const value=drafts[draftSlot(draftRoot,draftKey)]||editable({});editing=restored?.editing||'';for(const id of fields){if(id==='enabled')get(id).checked=value[id]!==false;else get(id).value=String(value[id]??'');}get('id').readOnly=!!editing;get('reload-latest').hidden=!editing;get('editor').hidden=!restored?.editorOpen;get('config-tool').value=restored?.configTool||'';get('client-id').value=restored?.clientId||'';
    return{refresh,items:()=>items,templates:()=>templates};
  }
  return{mount,capture,options,enabled,canQueue,evidence,editable,esc};
});
