(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.AIHubWorkcenter=factory();})(globalThis,function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rows=v=>Array.isArray(v)?v:Array.isArray(v?.items)?v.items:[];
  const categories={report:'工作报告',plan:'计划方案',requirement:'需求说明',delivery:'交付说明',reference:'参考资料',other_text:'其他文档',temp_candidate:'疑似临时'};
  const intake={registered:'明确登记',indexed:'来源已索引',legacy:'既有资料入口'};
  const tools={codex:'Codex',zcode:'ZCode',workbuddy:'WorkBuddy',dsh:'DSH',any:'通用来源',unknown:'来源待确认'};
  const statusNames={available:'可访问',missing:'文件缺失',rejected:'访问受限',unscanned:'未盘点'};
  const date=v=>{if(!v)return '时间未记录';const d=new Date(typeof v==='number'?v*1000:v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('zh-CN',{hour12:false});};
  const categoryOptions=selected=>Object.entries(categories).map(([value,label])=>`<option value="${value}" ${selected===value?'selected':''}>${label}</option>`).join('');
  function capture(el){
    const get=id=>el?.querySelector('#wc-'+id)?.value || '';
    return {drafts:{...el?._wcDrafts},query:get('query'),project_id:get('project'),category:get('category'),intake_status:get('intake'),tool:el?.dataset.wcTool || '',page:Number(el?.dataset.wcPage)||1,selected:el?.dataset.wcSelected || '',root:el?.dataset.wcRoot || '',classification:el?.dataset.wcReaderReady==='true'?{document_id:el?.dataset.wcSelected||'',category:get('edit-category'),project_name:get('edit-project')}:null};
  }
  function documentsHTML(items,selected){return rows(items).map(d=>`<button class="wc-document" data-wc-document="${esc(d.id)}" aria-pressed="${String(d.id)===String(selected)}"><span class="wc-document-title">${esc(d.title)}</span><span class="wc-document-meta"><span>${esc(tools[d.tool] || d.tool || '来源待确认')}</span><span>${esc(categories[d.category] || '其他文档')}${d.category_manual?' · 已校正':d.intake_status==='indexed'?' · 线索':''}</span><span>${esc(intake[d.intake_status] || '待确认')}</span><span>${esc(statusNames[d.status] || d.status || '')}</span></span><span class="wc-document-context">${esc(d.project_name || '未归属项目')}${d.project_origin==='inferred'?' · 目录推测，待确认':''} · ${esc(date(d.mtime))}</span></button>`).join('') || '<div class="wc-empty">当前条件下没有已收录文档。尝试清除筛选，或查看收录范围；没有结果不代表文件不存在。</div>';}
  function coverageHTML(coverage){
    const sources=rows(coverage?.sources),partial=Number(coverage?.partial_sources)||0,unscanned=Number(coverage?.unscanned_sources)||0,unavailable=Number(coverage?.unavailable_sources)||0;
    return `<div class="wc-coverage ${partial||unscanned||unavailable?'is-partial':''}"><div><strong>收录范围 · ${esc(coverage?.indexed_documents ?? 0)} 份来源文档已索引</strong><p>${partial?`${partial} 个来源盘点不完整。`:''}${unscanned?`${unscanned} 个来源尚未盘点。`:''}${unavailable?`${unavailable} 个来源不可访问。`:''}${coverage?.project_discovery_partial?'项目发现未完整。':''}以下结果仅覆盖已登记或发现的资料入口，不代表全机项目已纳入。</p></div><a class="btn small" href="#/collaboration?tab=sources">管理报告来源</a></div><details class="wc-source-list"><summary>查看来源范围与未完成项（${sources.length}）</summary>${sources.length?`<div class="table-wrap"><table class="tbl"><thead><tr><th>来源 / 目录</th><th>工具</th><th>收录状态</th></tr></thead><tbody>${sources.map(s=>`<tr><td>${esc(s.label || s.path)}<span class="file-sub pathline">${esc(s.path)}</span></td><td>${esc(tools[s.tool] || s.tool || '待确认')}</td><td>${s.registered===false?'未接入':s.status==='unavailable'?'不可访问':s.truncated?'未完整 · 达到预算或部分不可读':s.scanned_at?'已完成本次盘点':'未盘点'}<span class="file-sub">${esc(s.file_count ?? 0)} 份已盘点 · ${esc(s.visible_documents ?? s.file_count ?? 0)} 份可展示 · ${esc(s.excluded_documents ?? 0)} 份已排除 · ${esc(date(s.scanned_at))}</span>${s.error?`<span class="file-sub">${esc(s.error)}</span>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<p class="wc-empty">服务未提供来源明细，请进入报告来源管理核对已登记目录。</p>'}</details>`;
  }
  function projectCards(items){return rows(items).map(p=>`<article class="panel wc-project"><span class="badge">${p.origin==='inferred'?'目录推测 · 待确认':p.origin==='registered'?'已登记':'既有项目'}</span><h3>${esc(p.name)}</h3><p>${esc(tools[p.tool] || p.tool || '多来源 / 待确认')} · ${esc(statusNames[p.status] || p.status || '')}</p><div class="wc-project-counts"><span>${esc(p.document_count ?? 0)}<small>文档</small></span><span>${esc(p.report_count ?? 0)}<small>报告</small></span></div><p>${esc(p.path)}</p><div class="wc-actions"><button class="btn small" data-wc-project="${esc(p.id)}">查看项目文档</button></div></article>`).join('')||'<div class="wc-empty">当前收录范围内尚无项目。已发现的报告可先在文档中心查看；登记来源不会自动认领全部项目。</div>';}
  function createReports({api,heading,copyPath,registerKnowledge,generateReport}){
    let generation=0;
    return async function page(el,params=new URLSearchParams(),restored){
      const run=++generation,active=()=>el.isConnected&&generation===run;
      const state={query:restored?.query??params.get('query')??params.get('q')??'',project_id:restored?.project_id??params.get('project_id')??'',tool:restored?.tool??params.get('tool')??'',category:restored?.category??params.get('category')??'',intake_status:restored?.intake_status??params.get('intake_status')??'',page:restored?.page??Number(params.get('page')||1),selected:restored?.selected??params.get('document_id')??'',root:restored?.root||'',items:[],facets:{}};
      let listSerial=0,readSerial=0,mutating=false;const drafts={...restored?.drafts};el._wcDrafts=drafts;
      const get=id=>el.querySelector('#wc-'+id),post=(action,body)=>api('/api/workcenter/'+action,{body:state.root?{...body,_workspace_root:state.root}:body});
      el.classList?.add('workcenter-page');
      el.innerHTML=(heading?heading('项目与报告','按项目、工具和文档用途查找工作成果，明确知道哪些范围尚未收录。','WORK CENTER'):'<h2>项目与报告</h2>')+`<div class="wc-commandbar"><p>搜索范围：已收录的标题、路径及项目元数据；不搜索 AI 原生会话或全文。</p><div class="wc-actions"><button id="wc-register" class="btn small ghost">登记资料入口</button><button id="wc-generate" class="btn small ghost">生成索引报告</button><button id="wc-refresh" class="btn small">刷新文档</button></div></div><div id="wc-error" class="wc-error" role="alert"></div><div id="wc-message" role="status" aria-live="polite"></div><div id="wc-coverage"></div><div id="wc-tools" class="wc-tools" role="group" aria-label="来源工具"><button class="btn small" data-wc-tool="">全部来源</button>${Object.entries(tools).filter(([k])=>!['any','unknown'].includes(k)).map(([k,v])=>`<button class="btn small" data-wc-tool="${k}">${v} 文档</button>`).join('')}</div><form id="wc-filter-form" class="wc-filters"><label>文档关键词<input id="wc-query" type="search" maxlength="500" placeholder="标题、项目或路径"></label><label>所属项目<select id="wc-project"><option value="">全部项目</option></select></label><label>文档类别<select id="wc-category"><option value="">全部类别</option>${categoryOptions('')}</select></label><label>收录状态<select id="wc-intake"><option value="">全部收录状态</option>${Object.entries(intake).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label><button class="btn primary" type="submit">查找文档</button></form><div class="wc-layout"><section class="panel wc-documents"><div class="panel-head"><h3 id="wc-count">正在读取文档…</h3><button id="wc-reset" class="btn small ghost">清除筛选</button></div><div id="wc-list" class="wc-list"></div><div class="wc-pager"><button id="wc-prev" class="btn small" disabled>上一页</button><span id="wc-page-info"></span><button id="wc-next" class="btn small" disabled>下一页</button></div></section><section id="wc-reader" class="panel wc-reader" aria-label="文档阅读区"><div class="wc-empty">选择一份文档，阅读内容、打开所在文件夹或校正分类。盘点的类别仅为线索。</div></section></div>`;
      for(const [id,key]of[['query','query'],['category','category'],['intake','intake_status']])get(id).value=state[key];
      function markTools(){el.dataset.wcTool=state.tool;el.querySelectorAll('[data-wc-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.wcTool===state.tool)));}
      function error(e){get('error').textContent=e?.message||String(e||'');}
      async function readDocument(id,path){
        if(mutating)return;if(el.dataset.wcReaderReady==='true'&&state.selected&&get('edit-category')&&get('edit-project'))drafts[state.selected]={category:get('edit-category').value,project_name:get('edit-project').value};const serial=++readSerial;state.selected=id||'';el.dataset.wcSelected=state.selected;el.dataset.wcReaderReady='false';get('reader').innerHTML='<div class="wc-empty" role="status">正在读取文档…</div>';
        try{
          const data=await api('/api/workcenter/document?'+new URLSearchParams(id?{id}:{path}));if(!active()||serial!==readSerial)return;
          state.selected=data.id||id;el.dataset.wcSelected=state.selected;
          const item=state.items.find(d=>String(d.id)===String(state.selected))||data;
          get('reader').innerHTML=`<div class="panel-head"><h3>${esc(data.title || item.title)}</h3></div><div class="body"><div class="wc-actions"><button id="wc-reveal" class="btn small">打开所在文件夹</button><button id="wc-copy" class="btn small ghost">复制路径</button></div><dl class="wc-detail-meta"><dt>文档位置</dt><dd>${esc(data.path || item.path)}</dd><dt>项目 / 来源工具</dt><dd>${esc(item.project_name || '未归属项目')} · ${esc(tools[item.tool] || item.tool || '来源待确认')}</dd><dt>分类与收录依据</dt><dd>${esc(categories[item.category] || '类别待确认')}${item.category_manual?'（人工校正）':item.intake_status==='indexed'?'（路径分类线索，未审核正文）':''} · ${esc(intake[item.intake_status] || '已收录文档')} · ${esc(item.project_origin==='inferred'?'项目按目录推测，待人工确认':'仅改变索引分类，不移动文件')}</dd></dl>${data.preview_supported?`<pre class="wc-text">${esc(data.content)}</pre>${data.truncated?'<p class="warning-note">正文过长，仅显示受控预览片段；原文件保持完整。</p>':''}`:`<p class="wc-empty">${esc(data.reason || '当前格式不支持文本预览。可打开所在文件夹，在本机应用中阅读。')}</p>`}<details class="wc-classify"><summary>校正文档类别与项目显示名称</summary><form id="wc-classify-form"><label class="wc-field">文档类别<select id="wc-edit-category">${categoryOptions(item.category || 'other_text')}</select></label><label class="wc-field">项目显示名称<input id="wc-edit-project" value="${esc(item.project_name || '')}" maxlength="200"></label><p class="caption-note wide">只保存管理索引中的分类和名称，不修改正文、目录位置或原工具记忆。</p><button class="btn small primary wide" id="wc-save-classification">保存分类</button></form></details></div>`;
          if(drafts[state.selected]){get('edit-category').value=drafts[state.selected].category;get('edit-project').value=drafts[state.selected].project_name;}el.dataset.wcReaderReady='true';
          if(restored?.classification?.document_id===state.selected){get('edit-category').value=restored.classification.category || item.category || 'other_text';get('edit-project').value=restored.classification.project_name || '';restored={...restored,classification:null};}
          get('copy').onclick=async()=>{try{await copyPath(data.path || item.path);}catch(e){if(active())error(e);}};
          get('reveal').onclick=async()=>{if(mutating)return;mutating=true;get('reveal').disabled=true;error('');try{await post('reveal',{document_id:state.selected});if(active()&&serial===readSerial)get('message').textContent='已请求打开该文档所在文件夹。';}catch(e){if(active()&&serial===readSerial)error(e);}finally{mutating=false;if(active()&&serial===readSerial)get('reveal').disabled=false;}};
          get('classify-form').onsubmit=async event=>{event.preventDefault();if(mutating)return;mutating=true;get('save-classification').disabled=true;error('');
            const body={document_id:state.selected,category:get('edit-category').value,project_name:get('edit-project').value.trim()};
            try{await post('classify',body);if(!active()||serial!==readSerial)return;delete drafts[state.selected];get('message').textContent='分类已保存，原文件未移动。';await load();}
            catch(e){if(active()&&serial===readSerial)error(e);}finally{mutating=false;if(active()&&serial===readSerial&&get('save-classification'))get('save-classification').disabled=false;}
          };
          el.querySelectorAll('[data-wc-document]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.wcDocument===String(state.selected))));
        }catch(e){if(active()&&serial===readSerial){get('reader').innerHTML=`<div class="wc-empty">文档暂不可读：${esc(e.message)}</div>`;error(e);}}
      }
      async function load(){
        const serial=++listSerial;error('');get('refresh').disabled=true;get('count').textContent='正在读取文档…';
        const query=new URLSearchParams({...Object.fromEntries(['query','project_id','tool','category','intake_status'].map(k=>[k,state[k]])),page:String(state.page),page_size:'30'});
        try{const data=await api('/api/workcenter/documents?'+query);if(!active()||serial!==listSerial)return;
          state.items=rows(data);const nextRoot=data.root||data.workspace_root||state.root;if(state.root&&state.root!==nextRoot){state.selected='';el.dataset.wcSelected='';++readSerial;restored=null;el.dataset.wcReaderReady='false';Object.keys(drafts).forEach(k=>delete drafts[k]);get('reader').innerHTML='<p class="wc-empty">工作环境已切换，请重新选择文档。</p>';error('工作环境已切换，已清除旧文档选择，筛选文字保留。');}state.root=nextRoot;el.dataset.wcRoot=state.root;state.page=Number(data.page)||state.page;el.dataset.wcPage=String(state.page);
          state.facets=data.facets || {};get('tools').innerHTML='<button class="btn small" data-wc-tool="">全部来源</button>'+[...new Set(['codex','zcode','workbuddy','dsh',...rows(state.facets.tools).map(t=>t.value)])].filter(Boolean).map(t=>`<button class="btn small" data-wc-tool="${esc(t)}">${esc(tools[t]||t)} 文档</button>`).join('');bindTools();get('project').innerHTML='<option value="">全部项目</option>'+rows(state.facets.projects).map(p=>`<option value="${esc(p.value)}">${esc(p.label)} (${esc(p.count ?? 0)})</option>`).join('');get('project').value=state.project_id;
          get('coverage').innerHTML=coverageHTML(data.coverage);get('list').innerHTML=documentsHTML(state.items,state.selected);
          const total=Number(data.total)||0,pages=Math.max(1,Math.ceil(total/(Number(data.page_size)||30)));
          get('count').textContent=`${total.toLocaleString()} 份文档 · ${tools[state.tool] || (state.tool?'其他来源':'全部来源')}`;
          get('page-info').textContent=`第 ${state.page} / ${pages} 页 · 本页 ${state.items.length} 份`;get('prev').disabled=state.page<=1;get('next').disabled=state.page>=pages;
          el.querySelectorAll('[data-wc-document]').forEach(b=>b.onclick=()=>readDocument(b.dataset.wcDocument));
          markTools();
        }catch(e){if(active()&&serial===listSerial){error(e);get('count').textContent='文档列表暂不可用';get('prev').disabled=true;get('next').disabled=true;}}
        finally{if(active()&&serial===listSerial)get('refresh').disabled=false;}
      }
      for(const [id,action]of [['register',registerKnowledge],['generate',generateReport]]){get(id).hidden=!action;get(id).onclick=async()=>{if(!action||mutating)return;get(id).disabled=true;try{await action(active);}catch(e){if(active())error(e);}finally{if(active())get(id).disabled=false;}};}
      get('filter-form').onsubmit=e=>{e.preventDefault();if(mutating)return;for(const[id,key]of[['query','query'],['project','project_id'],['category','category'],['intake','intake_status']])state[key]=get(id).value.trim();state.page=1;return load();};
      function bindTools(){el.querySelectorAll('[data-wc-tool]').forEach(b=>b.onclick=()=>{if(mutating)return;state.tool=b.dataset.wcTool;state.page=1;markTools();return load();});}bindTools();
      get('prev').onclick=()=>{if(state.page>1&&!mutating){state.page--;return load();}};get('next').onclick=()=>{if(!get('next').disabled&&!mutating){state.page++;return load();}};
      get('refresh').onclick=()=>!mutating&&load();get('reset').onclick=()=>{if(mutating)return;for(const key of['query','project_id','tool','category','intake_status'])state[key]='';for(const id of['query','project','category','intake'])get(id).value='';state.page=1;markTools();return load();};
      markTools();await load();if(active()&&(state.selected||params.get('path')))await readDocument(state.selected,params.get('path'));
    };
  }
  function createProjects({api,heading,nav,legacyPage}){
    return async(el,params=new URLSearchParams(),restored)=>{
      const legacy=params.get('view')==='registry';el.classList?.add('workcenter-page');el.dataset.wcView=legacy?'registry':'documents';
      el.innerHTML='<div class="wc-section-switch"><a class="btn '+(!legacy?'primary':'')+'" href="#/projects">跨工具项目索引</a><a class="btn '+(legacy?'primary':'')+'" href="#/projects?view=registry">项目与运行登记</a></div><div id="wc-project-content"></div>';
      const host=el.querySelector('#wc-project-content');
      if(legacy)return legacyPage(host,params,restored?.legacy || restored);
      host.innerHTML=(heading?heading('跨工具项目','关联各工具的项目资料与工作报告，保留原工具的创作主档案。','PROJECT INDEX'):'<h2>跨工具项目</h2>')+'<div id="wc-project-error" class="wc-error" role="alert"></div><p class="caption-note">目录推测只用于查找资料，不能代替正式项目登记。需要调整资产位置与运行证据时，进入「项目与运行登记」。</p><div id="wc-project-coverage"></div><div id="wc-project-cards" class="wc-project-grid"></div><div id="wc-project-pager" class="wc-pager"></div>';
      let page=Number(params.get('page'))||1,serial=0;
      async function load(){const request=++serial;try{const data=await api('/api/workcenter/projects?'+new URLSearchParams({page:String(page),page_size:'30'}));if(!el.isConnected||request!==serial)return;el.dataset.wcRoot=data.root||data.workspace_root||'';host.querySelector('#wc-project-cards').innerHTML=projectCards(data.items);if(data.coverage)host.querySelector('#wc-project-coverage').innerHTML=coverageHTML(data.coverage);host.querySelectorAll('[data-wc-project]').forEach(b=>b.onclick=()=>nav('reports',{project_id:b.dataset.wcProject}));const total=Number(data.total)||0,pages=Math.max(1,Math.ceil(total/(data.page_size||30)));host.querySelector('#wc-project-pager').innerHTML=`<button id="wc-project-prev" class="btn small" ${page<=1?'disabled':''}>上一页</button><span>共 ${total} 个项目 · 第 ${page} / ${pages} 页</span><button id="wc-project-next" class="btn small" ${page>=pages?'disabled':''}>下一页</button>`;host.querySelector('#wc-project-prev').onclick=()=>nav('projects',{page:page-1});host.querySelector('#wc-project-next').onclick=()=>nav('projects',{page:page+1});}
      catch(e){if(el.isConnected&&request===serial)host.querySelector('#wc-project-error').textContent=e.message;}}
      await load();
    };
  }
  return {createReports,createProjects,capture,esc,documentsHTML,coverageHTML,projectCards};
});
