const test=require('node:test'),assert=require('node:assert/strict');
const ui=require('../frontend/workcenter.js');
const doc={id:'d1',title:'报告',path:'D:/Studio/report.md',project_id:'p1',project_name:'电影',project_origin:'inferred',tool:'codex',category:'report',intake_status:'indexed',status:'available'};
function harness(handler){const nodes=new Map(),requests=[];const get=s=>{if(!nodes.has(s))nodes.set(s,{value:'',textContent:'',innerHTML:'',disabled:false,dataset:{},querySelector:selector=>get(selector),querySelectorAll:()=>[],setAttribute(){}});return nodes.get(s);};const el={isConnected:true,dataset:{},innerHTML:'',classList:{add(){}},querySelector:get,querySelectorAll:()=>[]};const api=async(url,opts)=>{requests.push({url,body:opts?.body});if(handler){const val=await handler(url,opts?.body);if(val!==undefined)return val;}if(url.startsWith('/api/workcenter/documents?'))return{items:[doc],total:65,page:Number(new URLSearchParams(url.split('?')[1]).get('page')),page_size:30,workspace_root:'D:/Studio',facets:{projects:[{value:'p1',label:'电影',count:65}]},coverage:{sources:[]}};if(url.startsWith('/api/workcenter/document?'))return{...doc,preview_supported:true,content:'<script>danger()</script>'};return{};};return{el,requests,key:id=>get('#wc-'+id),page:ui.createReports({api,copyPath:async()=>{}}),api};}
const submit=()=>({preventDefault(){}});

test('optional templates do not appear as report sources without registration or historical documents',async()=>{
  const h=harness(url=>url==='/api/harnesses'?{items:[],templates:[{id:'codex',name:'Codex'}]}:url.startsWith('/api/workcenter/documents?')?{items:[],total:0,page:1,page_size:30,workspace_root:'D:/Studio',facets:{tools:[]},coverage:{sources:[]}}:undefined);await h.page(h.el);
  assert(!h.key('tools').innerHTML.includes('codex'));assert.match(h.key('tools').innerHTML,/全部来源/);assert(!h.requests.some(r=>r.body));
});
test('workcenter escapes metadata, preview boundaries and reports incomplete coverage',()=>{const bad='<img src=x onerror=x>';for(const html of [ui.documentsHTML([{...doc,title:bad,path:bad,project_name:bad}],''),ui.projectCards([{name:bad,path:bad}]),ui.coverageHTML({sources:[{label:bad,path:bad,truncated:1}],partial_sources:1,unavailable_sources:1,project_discovery_partial:true})]){assert(!html.includes('<img'));assert(html.includes('&lt;img'));}const html=ui.coverageHTML({sources:[{label:'训练',truncated:1,file_count:2000,visible_documents:4,excluded_documents:1996},{label:'缺失',scanned_at:123,status:'unavailable'}],partial_sources:1,unavailable_sources:1});assert.match(html,/未完整/);assert.match(html,/不可访问/);assert.match(html,/1996 份已排除/);assert.match(html,/不代表全机项目已纳入/);});
test('server filters and pagination use confirmed query names and preserve query text',async()=>{const h=harness();await h.page(h.el);h.key('query').value='Codex 交付';h.key('project').value='p1';h.key('category').value='delivery';h.key('intake').value='indexed';await h.key('filter-form').onsubmit(submit());await h.key('next').onclick();const q=new URLSearchParams(h.requests.filter(r=>r.url.startsWith('/api/workcenter/documents?')).at(-1).url.split('?')[1]);assert.equal(q.get('query'),'Codex 交付');assert.equal(q.get('project_id'),'p1');assert.equal(q.get('category'),'delivery');assert.equal(q.get('intake_status'),'indexed');assert.equal(q.get('page'),'2');assert.equal(q.get('page_size'),'30');});
test('safe reader supports old path links without rendering arbitrary HTML',async()=>{const h=harness();await h.page(h.el,new URLSearchParams({path:doc.path}));assert(h.requests.some(r=>r.url.includes('document?path=')));assert.match(h.key('reader').innerHTML,/&lt;script&gt;/);assert(!h.key('reader').innerHTML.includes('<script>'));assert(!h.requests.some(r=>r.body));await h.key('reveal').onclick();assert.deepEqual(h.requests.at(-1).body,{document_id:'d1',_workspace_root:'D:/Studio'});});
test('manual classification is explicit and failure preserves draft with root guard',async()=>{const h=harness((url)=>{if(url.endsWith('/classify'))throw Error('工作环境不匹配');});await h.page(h.el,new URLSearchParams({document_id:'d1'}));h.key('edit-category').value='plan';h.key('edit-project').value='新显示名';assert(!h.requests.some(r=>r.body));await h.key('classify-form').onsubmit(submit());assert.deepEqual(h.requests.at(-1).body,{document_id:'d1',category:'plan',project_name:'新显示名',_workspace_root:'D:/Studio'});assert.match(h.key('error').textContent,/不匹配/);assert.equal(h.key('edit-project').value,'新显示名');assert.equal(h.key('save-classification').disabled,false);});
test('navigation snapshot restores filters, selected doc and classification drafts',async()=>{const h=harness();await h.page(h.el,new URLSearchParams({document_id:'d1'}));h.key('query').value='未提交搜索';h.key('edit-project').value='未保存名';h.key('edit-category').value='reference';const snapshot=ui.capture(h.el);const next=harness();await next.page(next.el,new URLSearchParams(),snapshot);assert.equal(next.key('query').value,'未提交搜索');assert.equal(next.key('edit-project').value,'未保存名');assert.equal(next.key('edit-category').value,'reference');});
test('workspace switch clears stale selection before any document read or write',async()=>{const h=harness();await h.page(h.el,new URLSearchParams(),{root:'E:/Old',selected:'old',query:'保留'});assert.match(h.key('error').textContent,/工作环境已切换/);assert.equal(h.key('query').value,'保留');assert(!h.requests.some(r=>r.url.includes('/document?')));assert.equal(h.el.dataset.wcSelected,'');});
test('late responses leave disconnected views untouched and failures allow retry',async()=>{let resolve;const wait=new Promise(r=>resolve=r);const h=harness(()=>wait);const pending=h.page(h.el);h.el.isConnected=false;h.key('count').textContent='new';resolve({items:[]});await pending;assert.equal(h.key('count').textContent,'new');const f=harness(()=>{throw Error('断开');});await f.page(f.el);assert.match(f.key('error').textContent,/断开/);assert.equal(f.key('refresh').disabled,false);});
test('project index preserves the legacy registry and exposes server pagination',async()=>{let called=0;const h=harness(url=>url.startsWith('/api/workcenter/projects?')?{items:[],total:80,page_size:30}:undefined);const page=ui.createProjects({api:h.api,nav:()=>{},legacyPage:async()=>called++});await page(h.el,new URLSearchParams({view:'registry'}),{legacy:{draft:'x'}});assert.equal(called,1);assert.equal(h.el.dataset.wcView,'registry');await page(h.el);assert(h.requests.some(r=>r.url.endsWith('page=1&page_size=30')));});

test('report filters include custom and disabled work-ends without hiding historical documents',async()=>{
  const h=harness(url=>url==='/api/harnesses'?{items:[{id:'custom-worker',name:'自定义工作端',enabled:true},{id:'codex',name:'历史 Codex',enabled:false}]}:undefined);
  await h.page(h.el);assert.match(h.key('tools').innerHTML,/custom-worker/);assert.match(h.key('tools').innerHTML,/历史 Codex（已停用）/);assert.match(h.key('list').innerHTML,/报告/);
});
